on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Make a release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/release-please-action
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
          pull-request-title-pattern: 'release${component} ${version}'
          pull-request-header: ':robot: I have created a release. Changelog updated with this data:'
      - uses: actions/checkout@v2
      # If we didn't create a release, we may have created or updated a PR.
      - run: |
            # Check out the branch that release-please created, if it exists.
            git fetch
            git checkout release-please--branches--main || exit 0
            # If it does exist, update manifest.json in the PR branch.
            # release-please can't update it for us yet.  See:
            # https://github.com/googleapis/release-please/issues/1171
            VERSION=$(jq -r .version package.json)
            cp core/version.json version.json.orig
            jq -r ".version = \"$VERSION\"" version.json.orig > core/version.json
            git add core/version.json
            # Emulate the author of the existing commit (the bot).
            git config user.email "$(git log -n 1 --format='%ae')"
            git config user.name "$(git log -n 1 --format='%an')"
            # Update the PR.
            git commit --amend --no-edit
            git push -f
        if: ${{ ! steps.release.outputs.release_created }}